# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validation:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project_path: 
        - "Advanced/Build-Post-TagSourcesWithBuildId/"
        - "Advanced/Build-Pre-CheckBranchBeforeDeployment/"
        - "Advanced/Build-Pre-CheckBranchBeforeDeploymentVerbose/"
        - "Advanced/Release-Pre-CheckBranchBeforeDeployment/"
        - "Advanced/Release-Pre-CheckBranchBeforeDeploymentVerbose/"
        - "Build/Pre/"
        - "Build/Post/"
        - "Build/PrePost/"     
        - "Release/Pre/"
        - "Release/Post/"
        - "Release/PrePost/"
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Install package.json validator
        run: sudo npm install package-json-validator -g
    
      - name: Validate package.json
        run: pjv -f "${{ format('{0}{1}', matrix.project_path, 'project.json') }}"
    

